[package]
name = "vdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vdb_key = { path = "../vdb_key" }
vdb_value = { path = "../vdb_value" }
rusqlite = { version = "0.26.0" }
thiserror = "1.0"
log = "0.4"
